@echo on
set "ONNX_ML=1"
REM set USE_MSVC_STATIC_RUNTIME=0

set CMAKE_BUILD_TYPE=Release
set "CMAKE_ARGS=%CMAKE_ARGS% -DONNX_ML=1"
set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=Release"
set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_CXX_STANDARD=17"
set "CMAKE_ARGS=%CMAKE_ARGS% -DBUILD_SHARED_LIBS=ON"
set "CMAKE_ARGS=%CMAKE_ARGS% -DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
set "CMAKE_ARGS=%CMAKE_ARGS% -DProtobuf_USE_STATIC_LIBS=OFF"
REM -DONNX_USE_LITE_PROTO=ON 
set "CMAKE_ARGS=%CMAKE_ARGS% -DONNX_USE_LITE_PROTO=OFF"
set "CMAKE_ARGS=%CMAKE_ARGS% -DUSE_MSVC_STATIC_RUNTIME=0"
set "CMAKE_ARGS=%CMAKE_ARGS% -DPython_FIND_STRATEGY=LOCATION"
REM -DCMAKE_CXX_FLAGS="""/DPROTOBUF_USE_DLLS=1 /EHsc /std:c++17"""
set "CMAKE_ARGS=%CMAKE_ARGS% -DNPY_TARGET_VERSION=NPY_1_19_API_VERSION"

%PYTHON% -m pip install --no-deps --ignore-installed --verbose .
