{% set name = "onnx" %}
{% set version = "1.3.0" %}
{% set sha256 = "fa7d4fe66164303e94e2bf5169f751abdba9f9a565bbeb22f54b5497d1388ebe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip:
    - true  # need C++11, so have to skip on:  # [win and vc<14]
    - true  # temporary, see #14 - # [win]
  script:
    - export ONNX_ML=1               # [unix]
    - set "ONNX_ML=1"                # [win]
    - export CONDA_PREFIX="$PREFIX"  # build script looks at this, but not set on  # [unix]
    - python -m pip install --no-deps --ignore-installed --verbose .
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - protobuf
    - libprotobuf
    - pytest-runner
    - ninja
  run:
    - python
    - protobuf
    - libprotobuf
    - numpy
    - six

test:
  imports:
    - onnx
  commands:
    - check-model --help
    - check-node --help
    - backend-test-tools --help
    - conda inspect linkages -p $PREFIX {{ name }}  # [unix]
    - conda inspect objects -p $PREFIX {{ name }}   # [osx]

about:
  home: https://github.com/onnx/onnx/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open Neural Network Exchange library
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).

extra:
  recipe-maintainers:
    - ezyang
    - dougalsutherland
