schema_version: 1

context:
  name: onnx
  version: "1.20.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/onnx/onnx/archive/v${{ version }}.tar.gz
  sha256: e9e9273cd39d460348aa3e2eb370a444b510e138c5f45dfa86ce50461901257b
  patches:
    - 0001-Link-to-abseil_dll.patch
    - 0002-Don-t-hide-all-symbols-and-set-ext-suffix.patch
    - 0003-Update-Cmake-definitons-for-conda-forge.patch
    - 0004-Adjust-nanobind-usage-for-conda-forge.patch
    - 0005-link-privately-and-abseil.patch
    - 0006-Link-to-libonnx.patch
    - 0007-Ensure-the-library-location-is-found.patch
    # https://github.com/onnx/onnx/pull/7532
    - 0008-Keep-windows-slashes.patch

build:
  number: 1
  python:
    entry_points:
      - check-model = onnx.bin.checker:check_model
      - check-node = onnx.bin.checker:check_node
      - backend-test-tools = onnx.backend.test.cmd_tools:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - nanobind
        - libprotobuf
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - libprotobuf
    - pip
    - protobuf
    - nanobind
    - setuptools
  run:
    - python
    - ml_dtypes
    - protobuf
    - typing_extensions

tests:
  - python:
      imports:
        - onnx
  - requirements:
      run:
        - pip
    script:
      - pip check
      - check-model --help
      - check-node --help
      - backend-test-tools --help
      - if: unix
        then:
          - test -f "${PREFIX}/lib/libonnx${SHLIB_EXT}"
          - test -f "${PREFIX}/lib/libonnx_proto${SHLIB_EXT}"
          - test -f "${PREFIX}/lib/cmake/ONNX/ONNXConfig.cmake"
      # - if: win
      #   then:
      #     - if not exist "%LIBRARY_PREFIX%\\bin\\onnx.dll" exit 1
      #     - if not exist "%LIBRARY_PREFIX%\\bin\\onnx_proto.dll" exit 1
      #     - if not exist "%LIBRARY_PREFIX%\\lib\\onnx.lib" exit 1
      #     - if not exist "%LIBRARY_PREFIX%\\bin\\onnx_proto.lib" exit 1

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Open Neural Network Exchange library
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).


  homepage: https://github.com/onnx/onnx/

extra:
  recipe-maintainers:
    - ezyang
    - marcelotrevisani
    - xhochy
    - janjagusch
    - cbourjau
